services:
  backend:
    image: school-api
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - path: .env
        required: true
